### ISSUE TITLE
Saved parcels disappear when you click on maps

### ISSUE THREAD

**Issue by d-diaz** [Ecotrust/landmapper#67]
I have two properties saved. When I click on Map in the top right corner of the website (http://landmapper.ecotrust.org/visualize) the page resets to zoom out of Oregon with the Properties tab turned on and tells me "You currently have no drawings." But then if I click Properties, the two properties I have mapped show up again. Since clicking Map seems to default to having the Properties tab activate, perhaps the Map link should point to http://landmapper.ecotrust.org/visualize#designs instead?

**Comment by rhodges** [comment]
@d-diaz There are some major bugs with reloading state in the MP stack right now. Reworking this (a task already underway) will be ongoing for quite some time and was not ready for this tool. 

Part of this rework will be more prevalent loading spinners (which is why you were told you had no properties - they were still loading).

Truth is, I don't know why we would want a 'Map' link in the header when you're already on the 'Map' - my current plan is to remove the button.

**Comment by rhodges** [comment]
Related to #71
